export const advancedWords = [
  "serendipity", "ephemeral", "mellifluous", "serene", "luminous", "ethereal", "resplendent", "magnificent",
  "eloquent", "profound", "enigmatic", "mysterious", "captivating", "mesmerizing", "enchanting", "bewitching",
  "sophisticated", "intricate", "elaborate", "complex", "sophisticated", "refined", "elegant", "graceful",
  "harmonious", "symphonic", "orchestral", "melodic", "rhythmic", "cadenced", "flowing", "fluid",
  "resilient", "tenacious", "persistent", "determined", "steadfast", "unwavering", "resolute", "committed",
  "innovative", "creative", "imaginative", "inventive", "original", "unique", "distinctive", "remarkable",
  "philosophical", "contemplative", "meditative", "reflective", "thoughtful", "introspective", "analytical",
  "scientific", "empirical", "methodical", "systematic", "logical", "rational", "reasonable", "sensible",
  "aesthetic", "artistic", "creative", "expressive", "imaginative", "visionary", "inspiring", "motivational",
  "intellectual", "scholarly", "academic", "educational", "informative", "enlightening", "illuminating",
  "spiritual", "transcendent", "mystical", "sacred", "divine", "heavenly", "celestial", "cosmic",
  "emotional", "passionate", "intense", "fervent", "ardent", "zealous", "enthusiastic", "excited",
  "psychological", "mental", "cognitive", "intellectual", "rational", "logical", "analytical", "critical",
  "sociological", "cultural", "social", "communal", "collective", "collaborative", "cooperative", "united",
  "technological", "digital", "electronic", "automated", "mechanized", "computerized", "programmed",
  "environmental", "ecological", "natural", "organic", "sustainable", "renewable", "conservation", "preservation",
  "economic", "financial", "monetary", "fiscal", "budgetary", "commercial", "business", "corporate",
  "political", "governmental", "administrative", "bureaucratic", "institutional", "constitutional", "democratic",
  "historical", "chronological", "temporal", "sequential", "progressive", "evolutionary", "developmental",
  "geographical", "spatial", "territorial", "regional", "local", "global", "international", "worldwide",
  "mathematical", "numerical", "quantitative", "statistical", "analytical", "computational", "algorithmic",
  "linguistic", "philological", "etymological", "semantic", "syntactic", "grammatical", "lexical", "vocabulary",
  "anthropological", "ethnographic", "cultural", "social", "human", "behavioral", "developmental", "evolutionary",
  "archaeological", "excavational", "discovery", "exploration", "investigation", "research", "study", "analysis",
  "astronomical", "cosmological", "celestial", "stellar", "planetary", "galactic", "universal", "cosmic",
  "biological", "organic", "living", "vital", "natural", "ecological", "environmental", "sustainable",
  "chemical", "molecular", "atomic", "elemental", "substance", "compound", "mixture", "solution",
  "physical", "material", "tangible", "concrete", "substantial", "solid", "firm", "stable",
  "mechanical", "engineering", "technical", "industrial", "manufacturing", "production", "construction", "building"
];
