export const simpleWords = [
  "the", "be", "to", "of", "and", "a", "in", "that", "have", "I",
  "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
  "this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
  "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
  "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
  "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
  "people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
  "than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
  "back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
  "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
  "here", "thing", "still", "try", "call", "hand", "eye", "find", "down", "may",
  "last", "go", "ask", "need", "feel", "three", "state", "never", "become", "between",
  "high", "really", "something", "another", "much", "family", "own", "out", "leave",
  "put", "mean", "keep", "let", "big", "group", "often", "run", "important", "until",
  "children", "side", "feet", "car", "night", "walk", "white", "sea", "began", "grew",
  "took", "river", "four", "carry", "state", "once", "book", "hear", "stop", "without",
  "second", "later", "miss", "idea", "enough", "eat", "face", "watch", "far", "Indian",
  "real", "almost", "let", "above", "girl", "sometimes", "mountain", "cut", "young",
  "talk", "soon", "list", "song", "being", "leave", "family", "it's", "body", "music",
  "both", "color", "stand", "sun", "questions", "fish", "area", "mark", "dog", "horse",
  "birds", "problem", "complete", "room", "knew", "since", "ever", "piece", "told",
  "usually", "didn't", "friends", "easy", "heard", "order", "red", "door", "sure",
  "become", "top", "ship", "across", "today", "during", "short", "better", "best",
  "however", "low", "hours", "black", "products", "happened", "whole", "measure",
  "remember", "early", "waves", "reached", "listen", "wind", "rock", "space", "covered",
  "fast", "several", "hold", "himself", "toward", "five", "step", "morning", "passed",
  "vowel", "true", "hundred", "against", "pattern", "numeral", "table", "north",
  "slowly", "money", "map", "farm", "pulled", "draw", "voice", "seen", "cold",
  "cried", "plan", "notice", "south", "sing", "war", "ground", "fall", "king",
  "town", "I'll", "unit", "figure", "certain", "field", "travel", "wood", "fire",
  "upon", "done", "English", "road", "half", "ten", "fly", "gave", "box", "finally",
  "wait", "correct", "oh", "quickly", "person", "became", "shown", "minutes", "strong",
  "verb", "stars", "front", "feel", "fact", "inches", "street", "decided", "contain",
  "course", "surface", "produce", "building", "ocean", "class", "note", "nothing",
  "rest", "carefully", "scientists", "inside", "wheels", "stay", "green", "known",
  "island", "week", "less", "machine", "base", "ago", "stood", "plane", "system",
  "behind", "ran", "round", "boat", "game", "force", "brought", "understand", "warm",
  "common", "bring", "explain", "dry", "though", "language", "shape", "deep", "thousands",
  "yes", "clear", "equation", "yet", "government", "filled", "heat", "full", "hot",
  "check", "object", "am", "rule", "among", "noun", "power", "cannot", "able", "six",
  "size", "dark", "ball", "material", "special", "heavy", "fine", "pair", "circle",
  "include", "built", "can't", "matter", "square", "syllables", "perhaps", "bill",
  "felt", "suddenly", "test", "direction", "center", "farmers", "ready", "anything",
  "divided", "general", "energy", "subject", "Europe", "moon", "region", "return",
  "believe", "dance", "members", "picked", "simple", "cells", "paint", "mind",
  "love", "cause", "rain", "exercise", "eggs", "train", "blue", "wish", "drop",
  "developed", "window", "difference", "distance", "heart", "site", "sum", "summer",
  "wall", "forest", "probably", "legs", "sat", "main", "winter", "wide", "written",
  "length", "reason", "kept", "interest", "arms", "brother", "race", "present",
  "beautiful", "store", "job", "edge", "past", "sign", "record", "finished", "discovered",
  "wild", "happy", "beside", "gone", "sky", "grass", "million", "west", "lay",
  "weather", "root", "instruments", "meet", "third", "months", "paragraph", "raised",
  "represent", "soft", "whether", "clothes", "flowers", "shall", "teacher", "held",
  "describe", "drive", "cross", "speak", "solve", "appear", "metal", "son", "either",
  "ice", "sleep", "village", "factors", "result", "jumped", "snow", "ride", "care",
  "floor", "hill", "pushed", "baby", "buy", "century", "outside", "everything",
  "tall", "already", "instead", "phrase", "soil", "bed", "copy", "free", "hope",
  "spring", "case", "laughed", "nation", "quite", "type", "themselves", "temperature",
  "bright", "lead", "everyone", "method", "section", "lake", "iron", "within",
  "dictionary", "hair", "age", "amount", "scale", "pounds", "although", "per",
  "broken", "moment", "tiny", "possible", "gold", "milk", "quiet", "natural",
  "lot", "stone", "act", "build", "middle", "speed", "count", "cat", "someone",
  "sail", "rolled", "bear", "wonder", "smiled", "angle", "fraction", "Africa",
  "killed", "melody", "bottom", "trip", "hole", "poor", "let's", "fight", "surprise",
  "French", "died", "beat", "exactly", "remain", "dress", "iron", "couldn't", "fingers",
  "row", "least", "catch", "climbed", "wrote", "shouted", "continued", "itself",
  "else", "plains", "gas", "England", "burning", "design", "joined", "foot",
  "east", "pay", "single", "touch", "information", "express", "mouth", "yard",
  "equal", "decimal", "themselves", "sight", "glad", "chose", "pretty", "solution",
  "fresh", "search", "suffix", "especially", "shoes", "actually", "nose", "afraid",
  "dead", "sugar", "adjective", "fig", "office", "huge", "gun", "similar", "death",
  "score", "forward", "suggested", "deal", "eaten", "avoid", "depend", "written",
  "board", "effect", "dark", "master", "street", "cried", "plan", "notice", "south",
  "sing", "war", "ground", "fall", "king", "town", "I'll", "unit", "figure",
  "certain", "field", "travel", "wood", "fire", "upon", "done", "English", "road",
  "half", "ten", "fly", "gave", "box", "finally", "wait", "correct", "oh", "quickly"
];
